### ISSUE TITLE
Шрифты с засечками

### ISSUE THREAD

**Issue by code-of-kpp** [svetasmirnova/tex-templates#1]
Я так понимаю, что в основном, в презентациях с этим стилем будут шрифты с тонким очертанием и засечками, а их не очень удобно читать не в книгах и статьях.

**Comment by svetasmirnova** [comment]
С засечками - это Serif? Там Sans Serif шрифты для основного текста. С засечками там для кода только. Я сейчас добавила PDF, который у меня компилируется. Вы тоже соберите пример и сравните. Если считаете, что лучше другие шрифты из стандартной поставки, скажите какие.

**Comment by code-of-kpp** [comment]
Не было fonts-extra
